repo: https://github.com/VocaHQ/vocalinux#main
primary_contact: kanishk@vocahq.com
auto_ccs:
  - jatin@vocahq.com
homepage: https://vocalinux.com
disabled: false
dockerfile: .oss-scanner/Dockerfile
threat_model: .oss-scanner/threat_model.md
