repo: https://github.com/tinyauthapp/tinyauth
primary_contact: security@tinyauth.app
homepage: https://tinyauth.app/
pgp: |
  -----BEGIN PGP PUBLIC KEY BLOCK-----

  mDMEar0QuxYJKwYBBAHaRw8BAQdAHNSl6tXWGbmlA2c++H5RYz4TfL6gdrpEDFl1
  3+IQ5Vy0JlN0YXZyb3MgRW1haWwgPHN0ZXZlaWxpb3A1NkBnbWFpbC5jb20+iJkE
  ExYKAEEWIQRfqNpr7QNMwyKr+iJmA4xSqsMHwgUCar0QuwIbAwUJBaOagAULCQgH
  AgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRBmA4xSqsMHwg/iAP9LDNBi/Nv0yot4
  Xv7Z8nIP0mJ8gHMqZcDpQuTpyBSe6wD/dnvwjZUZhJBB53sxLdQ7rxTz5IrmfGHN
  8E9zgIVbAA64OARqvRC7EgorBgEEAZdVAQUBAQdA0+1HdQnP27jiyF0SZ7KPoP+W
  qU29kvSKyzZzGMRgRHADAQgHiH4EGBYKACYWIQRfqNpr7QNMwyKr+iJmA4xSqsMH
  wgUCar0QuwIbDAUJBaOagAAKCRBmA4xSqsMHwlVCAQDbNp8YavtNvudgWbLzTdiH
  waxY/C0QF9xw6KAMHMnrfwD+IvrHSKaMF+stHhraT/l21Xpn8f2dasZhM2M+xpei
  uwA=
  =jzvz
  -----END PGP PUBLIC KEY BLOCK-----
