repo: https://github.com/Colorado-Mesh/mesh-client
primary_contact: nv0n@coloradomesh.org
homepage: https://colorado-mesh.github.io/mesh-client/
dockerfile: .oss-scanner/Dockerfile
threat_model: .oss-scanner/threat_model.md
