repo: https://github.com/theupdateframework/go-tuf
primary_contact: rdimitrow@gmail.com
homepage: https://theupdateframework.io/
dockerfile: .oss-scanner/Dockerfile
threat_model: .oss-scanner/threat_model.md
