# IW4MAdmin: complete server administration tool for IW4x, Plutonium, and other Call of Duty / Source game servers.
repo: https://github.com/RaidMax/IW4M-Admin#develop

primary_contact: raidmax@live.com

homepage: https://github.com/RaidMax/IW4M-Admin

disabled: false
