repo: https://github.com/uutils/coreutils#main

primary_contact: sylvestre@debian.org

homepage: https://uutils.github.io/coreutils/

pgp: |
  -----BEGIN PGP PUBLIC KEY BLOCK-----

  mQINBEoIOd4BEACixY6QvbpPTUeIDozyQCjgKNbQ6M6u+pzYN/KnBMu79k73NANE
  MaeD5lvo9ZM7DgoHP3tQYeCeFIHreHSE3knHZ7FZ53dzW7fja9A3B0rXQGSr3ExC
  C86YlapOVVjNix7AGg+DNHZaAfM7No8HbVkMgxLAPpvj825wLZS7GFXfnuqhxF0H
  0cOrNf1opmgN71PfZ7rvVnsWC74ZxTySTO4vb0FMFqBOEFnJmcAqHlFwW2LVfaR9
  W71370bxl47Dhn/b5RyFvy3E27kbhWxUznyKLGnLCp1AWxW6hVPfqucnGV9D+dwu
  ARLNgnJcHynvh8lwpi79MpnQNNl0gFhYGD576aa+xgLj1YQVG1XgxraEQ37JL+jz
  im1kOSjEnMS60IKXA3RrP/U1LnOpI30QDJiq80auFmWdSvdeJPFkF21Bayit3hCu
  BLQlW+rYFouj4CSzgKSMkuNk9GKlxkRCPQuRgo+rPx+GmRkrA+4gGt4n3AlnRp14
  +eUy9FiXRw9pWEFFX9eu16B/BUV7Qa/zE6LzJfb+tsPiJyG7tvdwzMnGNvRew7WQ
  pXhcoo9vQ4XU2v5fcJslUH2vwtghgluKyFGGvSJ8c4hzoRpCxJyS9vRxt+uFVcS+
  PcgLeWD40csY802rW1H0zhfyyviMtuROYSuTCW2tyWR4ywWgpK1+K7fIAQARAQAB
  tCVTeWx2ZXN0cmUgTGVkcnUgPHN5bHZlc3RyZUBpcmlsbC5vcmc+iQI4BBMBCAAi
  BQJSVA8EAhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRB+ZSjadS8b4aSr
  D/41tGSw41KvlwWIpCVHaiMpOLxZyP6OzMRUftehqVyLq61zrnriOdrUv5lcXtpl
  05ajaDIlyIbTSd6RFx0DsG+wdc8VhhqAAmA8xu77oYOteXQf1cYAKVsEpojKcuzo
  12TeDArp7NdkYk++dpMSSgQw0jFf/UCMqBXO002NH3GHlduN/SLYjoN2McEjfuE8
  VF2RrVYAgi8OljtB6oSAAKGXKgAmimpKkMN2zyoHNlvvdtVpB7z90Sk+qeHDUAUD
  +sCbZfs6Kv9WiVXnXLUmt2O6/+ANKmKfliI9LYmejDJMYpkQ1XNdlUtzMx64+JkH
  F4XYPi/Llbolh/vlXXdXzW3NW3R+tpTCXALbhq0NCPntA2mXR1fDbeUcXvcyTnmM
  I5hCDOddVgfCL/jM7coPPcVt3XF52eR5ODwBykmuhYQ5QeMl72kMAFhiflslV6ag
  zXBNdWKUSyNRvdX5wbjUjpazJut3VpsfI82mrUZlxMl4DQpodOPAaj9Z9Eb+SKcd
  gHu+WFeaRRjlpIdV+QdyLxCxMyZYHHZQ85fAf3RSm2yBlW3GEb1SpgvWyEA8b8pj
  nmwF92g0TPVcjtUNzXUuW803UFXIiSC2IbgyAbxuuyE5mGzITvMV+GJBoVU5qo/+
  bHKVNxKvqzzeRUNMkeszURdXwAxWyu8u2C2PtdLTXQf/frQmU3lsdmVzdHJlIExl
  ZHJ1IDxzeWx2ZXN0cmVAZGViaWFuLm9yZz6JAjkEEwEIACMCGwMGCwkIBwMCBBUC
  CAMEFgIDAQIeAQIXgAUCUqnFzAIZAQAKCRB+ZSjadS8b4WbwD/4h7EfniLRPFyZo
  w9HKvAg3PEv6QmDJEYKKMGiEsZdij78S52D3gIdesZFqckeqx9TeVuDF9y7kv8ey
  m2EZhmIh3CZNLgZIC8vUETNkaJ0cSgwTPAoVNH0JTKRSvxDiWbmCrQCVw5ubBtz3
  T2Z+B3lY9CSxUwUiqytQvHgfgnZdsbwUiTPf96CdFdNK2HwEJlgsTuFdsy18uHTZ
  c2rpu1V06rNKMPBh/Vf7/6eaPKQzXOk0XYi7W8f5pDYkV0xeo7QisI4DHZEpbViG
  nNk1trGsOdvtPtB9P2LPVdstZMbue4qrbrjZqNuiq6z6U6EdTMShmsOHWT+zSADi
  V9bNGgKLDff6YmK5jM21TU+Z4f/cHq5S1uO3ztLFAL0UHa6e4cS9EXKATsEm0Vd5
  ks402cvRt9Pqif4aDm2/Bp7TBswanSUFlClngiNYqUMRsf1ewXLK7D8CAvH2cKGC
  n78G46zgvlcnYw36+Ss/QrFSdESYOGP2/48/Mh9SxZ6bRnwdw+qQZY9ihmRtGTBn
  KP+rcMf1Rdnmrh9pLJa4znwwlRgf0oHz5C2CQ+oqhuiwuv/rbQrIwpn1bA2BF+Y7
  vChc7fVMxthrqfyK0iY7m8ePYBoWt4I2cXx0PNLMi71o4SbzxQ+LeHo/MWZZGBNO
  R3rxkdo5TRZ+ynIbrvF+lITFIVqRH7QmU3lsdmVzdHJlIExlZHJ1IDxzeWx2ZXN0
  cmVAbGVkcnUuaW5mbz6JAjcEEwECACECGwMCHgECF4AFAkoIOsoFCwkIBwMFFQoJ
  CAsFFgIDAQAACgkQfmUo2nUvG+E0tA/+OejGHXUiRDrqJqm8vQNpniGfoapy5AA5
  yykun7FXplLbdP/2swz5NlFZpSNmztFjW92dwIyQAy0COnEpJPjXvZ7fL+MLhKZW
  jxhVtI5ZytRMXAtarxZPHiLF6wiI0nuEROo0vs8S5mLITCcjCubpPaQ8GBcAlUrz
  dW1ASMKzJ9S0XW87ORi7snJgoIqTdg8tAVVnR5aJyhApKnpbGMZ3tRpBP/y8gOwK
  cVYTRkBz0t6lWpFx9VLQqhVprkXp+MwXWP3aZVdv4F6V8Tdrb0m6ZNPv/6haJwWh
  nCClZ9UlOBOskgxEgPJR9JLQzWjdfbvugX6v/LKPQcaVAFfAtzpvEgjVR2lgVZZL
  lQQLllSk18c/z4oS2UvJPS3wyoQRigkxwW+wUbkBpfeKz3w6hGHGBPfYFTgkJQVj
  aOHBnwgpnCEwHK9yHD8nNOKVZxjdlmfTxA+34sNRf/LuPMei6BTh0QCy7V6v4/4S
  gWVPYJT273gYT2SVOTRMQWea+MnrXeibEnx32nAobKMhtwfGsnikgEdXTdH1RLV2
  44yf3Zv/ooL13tIPKNY7Mtizv+uQIbGtO87V+v66uUAmBGNPgz0YNrIbyD0KMslD
  WzRg3pGL87khm0jnCDIiIqY/QIT6Kjbcpe5zq6qSrkZWTQBfpdKp/E6vTyUfVU/X
  99/qj3sN1Dq0JlN5bHZlc3RyZSBMZWRydSA8c3lsdmVzdHJlQHVidW50dS5jb20+
  iQI4BBMBCAAiBQJSVA8UAhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRB+
  ZSjadS8b4QFnD/9wMa/c23ojwGE3W3mV258JXD05px5c+eI2lkxJEU6TzTUmDUlb
  JCA0OKRBd3TrhVPXcq3Javl/eDzDIP64dRuz0lGEopj96nayISq+/MYPFhLxFWEk
  Vrl47seWE6P+nv9p0MsBdQ56+QPWkaBaJP4ZZLkGOCIiXqxEk/izYSBMmsJfn/E1
  hyQPENO8N6XHcGUXQM5Ko60j3x1p2ZR4A9zrm0rY+4Ue9xTz+7oWQ2VybBabSdtq
  +/Wf+guv01qsyxjfnHr/t3irNfzgRPgsDSZULs/DzZJgJVboVH8klWnerPiKHQSL
  0UOResl6p+n3aYhGJ2Q0nfCaeMNRK3DPqZ0TmYc8aQLnxxWDgNH5LCw5lrkhpNee
  1Y5HOHVz6GHWXVov7Qvh4eM1vmVisNz8L5a4lfrUC1wTKpXp8PaBog7nJaNbS2vc
  EqJi5xFm1tyg8/OaJl25/45xotnMZCqE+MDCJ2MOZljtz+L1apaPzQ/V2451Ignb
  pcHkgByzsjgIJWffOYylSVZ8iATE3P7op4G4OWL1ic2LMPgY6FJfm75bR5JjoIpC
  8Eozhhut6kkkNHFwl3cqGFaHPxXIxi5zgbQ0T1Gq3VS7Mba9E0MZFfexWwyKLslT
  s1zcSiklZHjUm8LWmRwgaBNBlUpxhIYuKwR/5ogT7lxj62jvEQVKouzRgbQqU3ls
  dmVzdHJlIExlZHJ1IDxzeWx2ZXN0cmUubGVkcnVAaW5yaWEuZnI+iQI3BBMBAgAh
  AhsDAh4BAheABQJKCDrJBQsJCAcDBRUKCQgLBRYCAwEAAAoJEH5lKNp1LxvhCDMP
  /RBH6yVu3btWUq1lq+ly/3IwmYaJjcgoeKoGpY8VPC8Z7qmWJCoKWh5RwZ42Jdxd
  219lcAeRcqJ/QkDvhmi132EI8LDS24U4H3/QylMlWDjwZM2lyq2v4hH+0e7iRPMI
  jJN6UFM3N1y5xIrNcsD9nde1oQSqF0ojUUlqVI2wBQuaj8OqPeSPPeIyNrW+AnUE
  FyKXByIDV24qecE0eraJBK8wMLFKlrJq/m4LgoYul20qtQGFYyht14fdJPTUfrk2
  ljpJXIor8tU0VXUpAzWneadJ95H4Ig2Uba5rGwNiSVLWi8J4g2/0s+XXKH9TDQYm
  +nDALr6qhiZLcZXODgm53jN/83fOprT4k7UkrBXwwmStpD7eiCLaBdL8EVahbhEG
  v+zhG5aLArOmCAKOG4rKR4Iuzfr70Te/EBdDhsEVzkE00RH0PN8inomIjkFWhHLr
  ezJgkjAK/CLp564zMTEgAosAm6/53B5qCGmycT5sFd2UIqApKD52pnNGKyAiJcX1
  2xfgba9ggd3F1AWWglVFeNMFC7GjJLuJnZLGHYpcDXPh0PdotW7nPDiQKkuXYrCH
  3IjgWt+g31/9MIALan4m/G/ibwmVvG+r9VwBWarbSIR85rrdBX0pZffvRxEXEHGF
  wJ6U21zHV+BZh4usckuGwmnb1U6OVacm/ITBm9bq1pgLtCxTeWx2ZXN0cmUgTGVk
  cnUgPHN5bHZlc3RyZS5sZWRydUBzY2lsYWIub3JnPokCHwQwAQgACQUCU7VuFwId
  IAAKCRB+ZSjadS8b4TV0EACemhC/ckTe4KU6vjSLFC8OLwO32pUHDLWAUAykGoAR
  27lmACw2BO/VStbUJPJZuoSKXHQhJvwzm/GoZversnp0zXbAqshpvbaaZphLhl/n
  aeZT/bEP8wD5Vj21hkcXoY/n5YTKSCpNBvVG2ggPK9KGN8VhlU9TjwKlXLYnJpK7
  IF0oVdG6PYMGMyonqHMiuDquS01cu3SFtSzLwnXk+jZijuHGwH43SzGHsCNgHx+1
  GL3EOAyfSxgPUY9EwXO3/eG0aEz/GgjJ5hcFqxG1gBPgPxJPek1DF2C7ySU50CBW
  YoVSPOrERyMeGKU1G6fA8pz901t1y83Bh+csRWqzNd1pFD6PZSqOEUPhNVyOXa62
  dKrkggOg/SU5bZEUE6nY4vZTqeaj5StaE1p9LKehNVDgD/7G7hLqfEICJo/KGljX
  GtM0zKUfZisHmE/Lw+HWOtCZZYMmuf2lx6bnjdkq4xRIw7u5B4x+FS7Qkkx+Rfxe
  MhqTVMIXafVyWjcMxMUTRvwTO+fM2JauludzG7q1Y1lLR/0h86xFqjnD/AV0gTYX
  HZb1KAXpsAsLlo/FOd0ZbgYcOUVbN5lxLG0ZxlxAcL698Jetv4ZOYkQFKhgboqAH
  w6V9F6ZO6F+eTVVD5zp+1GyNQF6tSTVwTt4VjT6Qi/NDq+3Q6eVq3PteQMzhZNwx
  o7QnU3lsdmVzdHJlIExlZHJ1IDxzeWx2ZXN0cmVAbW96aWxsYS5jb20+iQI4BBMB
  CAAiBQJS4BGiAhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRB+ZSjadS8b
  4d4hEACU3XWqW1CMeqHujYiDoXbGB+KzeYn9xE4OuJT7nyP5AuNneQoY7SF+/1k8
  zOgvlv6P1n/MNv/Vat7rUhy7jKVZd6yRD15GpB9bWUQzGXBWxA3opje+FfxtsqaR
  ZurhNuhWLCkvfUrERNCC9wUybtAqP63wO96gUwW5I7eiytZIVEKhJpudf076ZEtD
  QYX3JhH90BBS4uYMfaeKWWd1Yb2n97rZzbjy47Lu+8LlUa+InHVDdc854TnrS0IS
  rrPc9jKQXwJO+Su4VDeKuPJ0QR/gkMEt56Ou+9IzrVNbCcKXP+7rrfUbnZOmRpct
  56EMr24aFAvvbFfu2gRxhyvB2MCQNscEAK3QM7iMUGGjMzRCCPU3S7J+KfgQXfWe
  B2ozmU9Alqv6AL/mjH5GWH8BwGp4HB9n3xzL5HekrekXcqh+JqqlmzLXe1XYJ3Os
  qmHjJYEk3WZ9wdiLsYhacoDPjHM9/wtsHbANOHRgPm95Vboi+/T4WqfyuE179l8U
  wB53Ro9puJ7cG27XXybvSQ/yJ0hHNqSawQzJCwsdNBw2o5c7l3ShxbKR7yagD/Eo
  G8lYhQPfg2cxmxZEuvoLAe4GwAXC1nx0nLSOW5Dxhuti7ETBB0aPlmbRWY4SFIRR
  5Iv2iVAj4k1luiGuUAjxdgFZzaML3DxRsbMvKSAWLOCSpcKWGbQkU3lsdmVzdHJl
  IExlZHJ1IDxzbGVkcnVAbW96aWxsYS5jb20+iQI4BBMBCAAiBQJTtW5GAhsDBgsJ
  CAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRB+ZSjadS8b4eZBD/44blP6ILaoplh9
  y+bhjURbOmtvrqH+zSEijwI350ltiqkHi9zXoxW5GUpAOaJEpBC+SgA7+9Ld8quV
  hF2iLuYXVptsv6TacYbvp2Exwe+sWMahZmehV2eV/DFH+Yi6tc5rwbTcSKjqEkrC
  PEA3W/Hm1x0+nisXAhsCXEbM4yyGURZsOPnbykweXtQfYZlQiAIO1DhVnD2D4AB9
  WEWt9DvLymokACSbmzLp8rlnsw4khoROvpQn53vPl+5RG6XU54H1eWAJ/x1dWntG
  axlFGJBgiXvpBuce/vDAjvw1tBWBhgQ48NyqwTHrEdlNkEuWY4zaePhaBEUWt9B8
  hyM1EMBxSc5oqWT73XsFlW7ilRp3DaPi0R/wzJZCxLANQ5vhmSdbgslCPCqyRhS8
  TP+743MvQUL/0X4n9CR/YGWkC73d8O7irpMweJFKwyNctwNIH7q/JLAWkbnIs1h5
  2w4SLNNCngHQSTAQHBh8Wnr0pEc058wA4SbubPb6JGIfVYpLz8VcaEQLbrlpSx1f
  u+L4tao/dl6JgLWW67nqC3OckV74ZPDWA2e3jh7biE+6eq36RPqTkIMZ+l4Nm1MT
  tayaIATfeM2ZUbAfEAmEgCRHteOR/uLa9uK+tUQkdoybOL/XBbvj9iN59t1rA6wt
  eBQnyKQB1/fZKviRqDjvW4J69wUj7rQfU3lsdmVzdHJlIExlZHJ1IDxzQG1vemls
  bGEuY29tPokCOAQTAQgAIgUCVw5W+wIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgEC
  F4AACgkQfmUo2nUvG+HKaw/+JkOVubXJJrBMlP+Az/i8rQ/H2cb52YtAffpGxiWj
  rFH2wbjJwzbKz6UmYMf++YegF48Ka8jGSQcKiy4+Piid4zqUtyG+mJOZFN2gWF0/
  PcVkt46lhSLtlbEXIx/OHpmxS+oDpywtCqKKlSVZWceQe3ToezvfSQNygCCT94CI
  2F/axFpaBracNZkK12a2LsWXlT1jIykVpYfxPlQUYny/8HIMUZL02mc6sgY2p/MW
  KVz9pazzKixf6nhZflk4tutaLWs004ui5cJc4iv3JH2r0Iv4rd89XQ7A5kDw4ZmX
  hAAfaU04m3Ayvhqn3uK/nzTE+o093I/WKSZeJqWC3XdUFJsHX/KAtJPmoei89yOw
  t2+OXox4M6HcVonpiUbc/EsVvAl9wfagk0402R/Oz92sxisXzPuK4MlUnCZftKAf
  FAJoW8WJ9nLqYeONfvxJLbRUQXfvuhxJrC/RxxF9xO8649C5v1+T2aXHMWP/uOIS
  CKF8aelAW6NV/Ivsl/RAhDl1049ofcMt0jUN5PTcDuX11xpRClE+VK82CYfpp9D6
  5+w7KHXIe9BL9YUaiuYin3F49phD0wV4772DP3ISt7FvqQ0z/Bjs/8mo1iLl252v
  Cy/AiIcP0vmKlmDB9K5O+FXXpLdyM0hVb2sr5kBfLfRFik08BQvF/JES8U8Oq9L+
  qTy5Ag0ESgg68wEQAK2YDqPmIlzNJzTk0PoSTJ7t3O6bB4VlTWX5aqkZCpQe2AD0
  n524+o9mqmoQege8vQlRfP71xDRbvp8qSI+3R65FD8+3Fv8Ylk9K8QxvQY7ZTEUd
  QFrygxumMN5ddkpUYpV62SQXG/4id72JSXlECePOiUOiCjodicN1/e24YJoMmrDa
  XYweAlNGQ7Q6H8gpmy72TCVzmi2TDeoqZOW/B7w3kWS4zPCjn51FoqASPKKQUowg
  YbVzUaOhq/rSkuNq/J2QQZCUspGmR1lKsNvYY8qvMgv+eLwhubH7LJAQpFsN9JtS
  6TfGQmL6PQufiDsEB5YF93uGSHO9OBJDDH5d+zT9HoQdjQPKrsaiDy48jJvAceRo
  ynDy/BxWPNiA1z4tntde8tsGxHt8tBUzMUOGEVtfxyKS+ILHRjUHko0P/N8G1IFy
  dO+l/K04V2IpL3nZIRJxIiIixLS+4SZZs9WWvRWM4Nfd+lgWT7nFgyNMLu/aNLLP
  DgXmAEmn2nsNFKgDb7YaMrVI7sozU4+mXpGD+QBRkY4Y8WWQs9Vl6G6WXHgUbeTj
  cO+D6gnDbVwqBh9sfezrbbXYmDqaU1F/R68NU2zO+oaM8JGPWNSwzyWV0BKPwzNP
  b77Cj+gA7Fe0Gyqx8+y8zreKH7vabzvM5MRAVJs9yZQLrymEoV14MH6sXCSnABEB
  AAGJAh8EGAEIAAkFAkoIOvMCGwwACgkQfmUo2nUvG+HqHQ/6A+ZF774cwLnSI0qS
  EgNEPV3tHtibmFV4d9SN8SRnF/kgMsFSdKuRtmXGiWGvreuIgFR/8oozuLK5CrfX
  0g2AZx0CQcLPvV4KXgx9aWICBVVEaT9Md80E5zBx6BnXx/wBuH4JzPcwpE7XBZmk
  S2NVhNfsz4ALD4T9ltMY6h5xcs13ulJppqE5MrcR6XbPUb1GgezXgmwZC/Zoq557
  d0l5CQ/u45vkdGfYpi4t5C9o6JCoVQfAOTH9Wm/wdiwguGZKwYobnMTka2kDwlaE
  Sqh4QwpGW9p08gpYcEnMElUtKvESAj7T6FPUGAdkkn7Ko9NRN2akz8NSO242RhqP
  nyNVSmfmgOYwnkPn0PW2xH0DV/Ue8k9hZVo3MZyx/JnFPgi/a4A7IPoS8bBwG5fI
  6aXTGoHoEv+EINhXYs1BwtHsmoks2xLK9Zb2ScjShzXj/BErKDMeej+hD8L68KYJ
  632kF9WBh7Xkfh/0GCmFPg56GeaNW1/fFKbrstXSeDKdWj2hFUogqtDWKp2Rh531
  VNxFN5gIKXbMlpbCA84RCjnV22OoMSQlehWknSYy+yX+CtSBXRfLAPHZL9nUEMoO
  Fp9pjIbZCsp/MxjpxWXgzS1DOfLUuFaNBk3wtVXsL4nUQZIErhEtUEOimc9OkVMP
  9GzmEzHGPltDDXuuood2VqLy2hI=
  =FdLw
  -----END PGP PUBLIC KEY BLOCK-----

disabled: false
