repo: https://github.com/open-telemetry/opentelemetry-dotnet#main
primary_contact: security@opentelemetry.io
auto_ccs:
  - martin.costello@grafana.com
  - pkielkow@cisco.com
homepage: https://opentelemetry.io/docs/languages/dotnet/
disabled: false
dockerfile: .oss-scanner/Dockerfile
threat_model: .oss-scanner/threat_model.md
